sonar.projectKey=mvp-agent-client-local
sonar.projectName=MVP Agent Client Local
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.scm.disabled=true
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.typescript.tsconfigPaths=tsconfig.app.json
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts
