import type { AgentRecord, GraphConnectionRecord, GraphDataset, TeamRecord } from "./types";

const teams: TeamRecord[] = [
  {
    id: "team-iam",
    name: "IAM Team",
    key: "IAM",
    description: "Central identity control plane for lifecycle, access reviews and entitlement investigations.",
    status: "healthy",
    active: true,
    domain: "Identity Governance",
    agentIds: ["agent-iam-coordinator", "agent-jumpcloud", "agent-github-iam", "agent-iga"],
    coordinatorId: "agent-iam-coordinator",
    lastUpdated: "2026-03-17T19:12:00Z",
  },
  {
    id: "team-secops",
    name: "Security Operations Team",
    key: "SECOPS",
    description: "Operational security team focused on auth anomalies, investigations and response.",
    status: "warning",
    active: true,
    domain: "Security Operations",
    agentIds: ["agent-secops-coordinator", "agent-bigquery", "agent-jira-docs"],
    coordinatorId: "agent-secops-coordinator",
    lastUpdated: "2026-03-17T18:47:00Z",
  },
  {
    id: "team-platform",
    name: "Platform Engineering Team",
    key: "PLATFORM",
    description: "Platform automation, shared integrations and operational enablement for admin tooling.",
    status: "healthy",
    active: true,
    domain: "Platform Engineering",
    agentIds: ["agent-platform-coordinator", "agent-gcp-iam"],
    coordinatorId: "agent-platform-coordinator",
    lastUpdated: "2026-03-17T18:04:00Z",
  },
];

const agents: AgentRecord[] = [
  {
    id: "agent-iam-coordinator",
    name: "IAM Coordinator",
    summary: "Routes IAM investigations and change proposals.",
    description: "Primary orchestrator for IAM workflows, setup gating and final response consolidation.",
    teamId: "team-iam",
    type: "COORDINATOR",
    status: "healthy",
    capabilities: ["workflow routing", "setup sequencing", "response consolidation"],
    tags: ["orchestrator", "iam", "control-plane"],
    tools: ["catalog", "policy viewer"],
    mcps: ["jumpcloud", "github", "iga"],
    lastUpdated: "2026-03-17T19:14:00Z",
  },
  {
    id: "agent-jumpcloud",
    name: "JumpCloud Directory Analyst",
    summary: "Directory and authentication specialist.",
    description: "Investigates users, groups, devices, login events and directory drift in JumpCloud.",
    teamId: "team-iam",
    type: "ANALYST",
    status: "healthy",
    capabilities: ["directory lookup", "group tracing", "auth signal analysis"],
    tags: ["jumpcloud", "directory", "auth"],
    tools: ["directory reader", "event explorer"],
    mcps: ["jumpcloud"],
    lastUpdated: "2026-03-17T19:01:00Z",
  },
  {
    id: "agent-github-iam",
    name: "GitHub Access Analyst",
    summary: "Explains policy-as-code and repository mappings.",
    description: "Maps role definitions, bindings, PR history and configuration ownership across IAM repos.",
    teamId: "team-iam",
    type: "SPECIALIST",
    status: "warning",
    capabilities: ["repo mapping", "binding trace", "history review"],
    tags: ["github", "gcp", "policy-as-code"],
    tools: ["repo browser", "diff analyzer"],
    mcps: ["github"],
    lastUpdated: "2026-03-17T18:56:00Z",
  },
  {
    id: "agent-iga",
    name: "IGA Integration Agent",
    summary: "Access request, approval and reconciliation specialist.",
    description: "Handles entitlements, approvals, reconciliation diagnostics and role assignment state in the IGA layer.",
    teamId: "team-iam",
    type: "INTEGRATION",
    status: "healthy",
    capabilities: ["approval state", "role assignment lookup", "reconciliation diagnostics"],
    tags: ["iga", "approval", "reconciliation"],
    tools: ["iga api", "n8n webhook"],
    mcps: ["iga"],
    lastUpdated: "2026-03-17T18:59:00Z",
  },
  {
    id: "agent-secops-coordinator",
    name: "Security Ops Coordinator",
    summary: "Coordinates auth anomaly investigations.",
    description: "Prioritizes detections, escalations and operational triage across authentication-related incidents.",
    teamId: "team-secops",
    type: "COORDINATOR",
    status: "warning",
    capabilities: ["incident triage", "cross-source correlation", "response planning"],
    tags: ["secops", "orchestrator", "detections"],
    tools: ["incident router", "timeline composer"],
    mcps: ["bigquery", "jira"],
    lastUpdated: "2026-03-17T18:33:00Z",
  },
  {
    id: "agent-bigquery",
    name: "BigQuery Investigator",
    summary: "Analytics and threat signal correlation.",
    description: "Queries analytical tables for access anomalies, inventory drift and historical correlation.",
    teamId: "team-secops",
    type: "ANALYST",
    status: "error",
    capabilities: ["historical correlation", "finding generation", "inventory checks"],
    tags: ["bigquery", "analytics", "detections"],
    tools: ["sql runner", "finding writer"],
    mcps: ["bigquery"],
    lastUpdated: "2026-03-17T17:41:00Z",
  },
  {
    id: "agent-jira-docs",
    name: "Jira / Confluence Analyst",
    summary: "Operational context and documentation support.",
    description: "Brings runbooks, tickets, exceptions and post-incident context into operational analysis.",
    teamId: "team-secops",
    type: "SPECIALIST",
    status: "healthy",
    capabilities: ["runbook lookup", "ticket context", "process mapping"],
    tags: ["jira", "confluence", "documentation"],
    tools: ["docs search", "ticket reader"],
    mcps: ["jira", "confluence"],
    lastUpdated: "2026-03-17T18:02:00Z",
  },
  {
    id: "agent-platform-coordinator",
    name: "Platform Coordinator",
    summary: "Owns shared integrations and platform health.",
    description: "Coordinates platform enablement agents and shared service dependencies for the control plane.",
    teamId: "team-platform",
    type: "COORDINATOR",
    status: "healthy",
    capabilities: ["shared service routing", "platform governance", "dependency overview"],
    tags: ["platform", "shared-services", "orchestrator"],
    tools: ["service inventory", "control hooks"],
    mcps: ["github", "gcp"],
    lastUpdated: "2026-03-17T17:55:00Z",
  },
  {
    id: "agent-gcp-iam",
    name: "GCP IAM Analyst",
    summary: "Platform-side access and privilege posture specialist.",
    description: "Reviews privilege posture, project-level bindings and IAM propagation from the platform perspective.",
    teamId: "team-platform",
    type: "SPECIALIST",
    status: "unknown",
    capabilities: ["binding review", "project scope analysis", "privilege posture"],
    tags: ["gcp", "iam", "platform"],
    tools: ["asset browser", "binding explorer"],
    mcps: ["github", "gcp"],
    lastUpdated: "2026-03-17T17:30:00Z",
  },
];

const connections: GraphConnectionRecord[] = [
  { id: "c1", source: "team-iam", target: "agent-iam-coordinator", type: "contains", label: "team owns" },
  { id: "c2", source: "team-iam", target: "agent-jumpcloud", type: "contains", label: "team owns" },
  { id: "c3", source: "team-iam", target: "agent-github-iam", type: "contains", label: "team owns" },
  { id: "c4", source: "team-iam", target: "agent-iga", type: "contains", label: "team owns" },
  { id: "c5", source: "team-secops", target: "agent-secops-coordinator", type: "contains", label: "team owns" },
  { id: "c6", source: "team-secops", target: "agent-bigquery", type: "contains", label: "team owns" },
  { id: "c7", source: "team-secops", target: "agent-jira-docs", type: "contains", label: "team owns" },
  { id: "c8", source: "team-platform", target: "agent-platform-coordinator", type: "contains", label: "team owns" },
  { id: "c9", source: "team-platform", target: "agent-gcp-iam", type: "contains", label: "team owns" },
  { id: "c10", source: "agent-iam-coordinator", target: "agent-jumpcloud", type: "coordinates", label: "dispatches", critical: true },
  { id: "c11", source: "agent-iam-coordinator", target: "agent-github-iam", type: "coordinates", label: "dispatches" },
  { id: "c12", source: "agent-iam-coordinator", target: "agent-iga", type: "coordinates", label: "dispatches", critical: true },
  { id: "c13", source: "agent-secops-coordinator", target: "agent-bigquery", type: "coordinates", label: "triages via", critical: true },
  { id: "c14", source: "agent-secops-coordinator", target: "agent-jira-docs", type: "coordinates", label: "adds context" },
  { id: "c15", source: "agent-platform-coordinator", target: "agent-gcp-iam", type: "coordinates", label: "routes platform work" },
  { id: "c16", source: "agent-jumpcloud", target: "agent-iga", type: "depends_on", label: "cross-checks with" },
  { id: "c17", source: "agent-github-iam", target: "agent-gcp-iam", type: "depends_on", label: "shares policy context" },
  { id: "c18", source: "agent-bigquery", target: "agent-jira-docs", type: "uses_tooling", label: "validates against tickets" },
];

export const graphTestMock: GraphDataset = {
  teams,
  agents,
  connections,
};
