import type { PrismaClient } from "@prisma/client";

export async function ensureSchema(prisma: PrismaClient): Promise<void> {
  const sql = [
    `CREATE TABLE IF NOT EXISTS Team (
      id TEXT PRIMARY KEY,
      key TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      description TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );`,
    `CREATE TABLE IF NOT EXISTS User (
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      passwordHash TEXT NOT NULL,
      role TEXT NOT NULL,
      teamId TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(teamId) REFERENCES Team(id)
    );`,
    `CREATE TABLE IF NOT EXISTS "Group" (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      teamId TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(teamId) REFERENCES Team(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS Group_name_teamId_key ON "Group"(name, teamId);`,
    `CREATE TABLE IF NOT EXISTS GroupMembership (
      id TEXT PRIMARY KEY,
      groupId TEXT NOT NULL,
      userId TEXT NOT NULL,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(groupId) REFERENCES "Group"(id),
      FOREIGN KEY(userId) REFERENCES User(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS GroupMembership_groupId_userId_key ON GroupMembership(groupId, userId);`,
    `CREATE TABLE IF NOT EXISTS Agent (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT NOT NULL,
      prompt TEXT NOT NULL,
      emoji TEXT,
      avatarUrl TEXT,
      primaryModel TEXT,
      fallbackModels TEXT,
      reasoningEnabled BOOLEAN NOT NULL DEFAULT 0,
      temperature REAL,
      maxTokens INTEGER,
      addHistoryContext BOOLEAN NOT NULL DEFAULT 0,
      historySessions INTEGER,
      addStateContext BOOLEAN NOT NULL DEFAULT 0,
      knowledgeMode TEXT,
      knowledgeMaxResults INTEGER,
      knowledgeAddReferences BOOLEAN NOT NULL DEFAULT 1,
      knowledgeContextFormat TEXT,
      knowledgeFilters TEXT,
      tags TEXT NOT NULL,
      type TEXT NOT NULL,
      isGlobal BOOLEAN NOT NULL DEFAULT 0,
      visibility TEXT NOT NULL DEFAULT 'private',
      teamId TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(teamId) REFERENCES Team(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS Agent_name_teamId_key ON Agent(name, teamId);`,
    `CREATE TABLE IF NOT EXISTS Tool (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      description TEXT,
      callName TEXT,
      transport TEXT,
      endpoint TEXT,
      method TEXT,
      authRef TEXT,
      timeoutMs INTEGER,
      type TEXT NOT NULL,
      mode TEXT NOT NULL,
      policy TEXT NOT NULL,
      riskLevel TEXT NOT NULL,
      dataClassificationIn TEXT NOT NULL,
      dataClassificationOut TEXT NOT NULL,
      inputSchema TEXT NOT NULL,
      outputSchema TEXT NOT NULL,
      rateLimitPerMinute INTEGER NOT NULL DEFAULT 60,
      visibility TEXT NOT NULL DEFAULT 'private',
      teamId TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(teamId) REFERENCES Team(id)
    );`,
    `CREATE TABLE IF NOT EXISTS AgentTool (
      id TEXT PRIMARY KEY,
      agentId TEXT NOT NULL,
      toolId TEXT NOT NULL,
      canRead BOOLEAN NOT NULL DEFAULT 1,
      canWrite BOOLEAN NOT NULL DEFAULT 0,
      FOREIGN KEY(agentId) REFERENCES Agent(id),
      FOREIGN KEY(toolId) REFERENCES Tool(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS AgentTool_agentId_toolId_key ON AgentTool(agentId, toolId);`,
    `CREATE TABLE IF NOT EXISTS KnowledgeSource (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      url TEXT NOT NULL,
      tags TEXT NOT NULL,
      sourceType TEXT,
      sourceConfig TEXT,
      chunkSize INTEGER,
      chunkOverlap INTEGER,
      chunkStrategy TEXT,
      embeddingProvider TEXT,
      embeddingModel TEXT,
      vectorStoreProvider TEXT,
      vectorStoreIndex TEXT,
      retrievalMode TEXT,
      searchType TEXT,
      maxResults INTEGER,
      rerankerProvider TEXT,
      rerankerModel TEXT,
      metadataFilter TEXT,
      contextFormat TEXT,
      addContextInstructions BOOLEAN NOT NULL DEFAULT 0,
      addReferences BOOLEAN NOT NULL DEFAULT 1,
      syncStatus TEXT DEFAULT 'idle',
      lastSyncedAt DATETIME,
      lastSyncError TEXT,
      indexedDocuments INTEGER NOT NULL DEFAULT 0,
      visibility TEXT NOT NULL DEFAULT 'private',
      ownerTeamId TEXT NOT NULL,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(ownerTeamId) REFERENCES Team(id)
    );`,
    `CREATE TABLE IF NOT EXISTS AgentKnowledge (
      id TEXT PRIMARY KEY,
      agentId TEXT NOT NULL,
      knowledgeSourceId TEXT NOT NULL,
      FOREIGN KEY(agentId) REFERENCES Agent(id),
      FOREIGN KEY(knowledgeSourceId) REFERENCES KnowledgeSource(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS AgentKnowledge_agentId_knowledgeSourceId_key ON AgentKnowledge(agentId, knowledgeSourceId);`,
    `CREATE TABLE IF NOT EXISTS Handoff (
      id TEXT PRIMARY KEY,
      fromAgentId TEXT NOT NULL,
      toAgentId TEXT NOT NULL,
      conditionExpr TEXT,
      priority INTEGER NOT NULL DEFAULT 50,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(fromAgentId) REFERENCES Agent(id),
      FOREIGN KEY(toAgentId) REFERENCES Agent(id)
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS Handoff_fromAgentId_toAgentId_key ON Handoff(fromAgentId, toAgentId);`,
    `CREATE TABLE IF NOT EXISTS RoutingRule (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      ownerTeamId TEXT,
      targetAgentId TEXT NOT NULL,
      fallbackAgentId TEXT,
      keywords TEXT NOT NULL,
      tags TEXT NOT NULL,
      minScore REAL NOT NULL DEFAULT 0.2,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(ownerTeamId) REFERENCES Team(id),
      FOREIGN KEY(targetAgentId) REFERENCES Agent(id),
      FOREIGN KEY(fallbackAgentId) REFERENCES Agent(id)
    );`,
    `CREATE TABLE IF NOT EXISTS AuditLog (
      id TEXT PRIMARY KEY,
      actorId TEXT,
      actorRole TEXT NOT NULL,
      actorTeam TEXT,
      action TEXT NOT NULL,
      entityType TEXT NOT NULL,
      entityId TEXT,
      beforeJson TEXT,
      afterJson TEXT,
      correlationId TEXT NOT NULL,
      configVersionHash TEXT NOT NULL,
      denied BOOLEAN NOT NULL DEFAULT 0,
      reason TEXT,
      messageHash TEXT,
      createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(actorId) REFERENCES User(id)
    );`,
  ];

  for (const statement of sql) {
    await prisma.$executeRawUnsafe(statement);
  }

  const alterSql = [
    `ALTER TABLE Agent ADD COLUMN emoji TEXT;`,
    `ALTER TABLE Agent ADD COLUMN avatarUrl TEXT;`,
    `ALTER TABLE Agent ADD COLUMN primaryModel TEXT;`,
    `ALTER TABLE Agent ADD COLUMN fallbackModels TEXT;`,
    `ALTER TABLE Agent ADD COLUMN reasoningEnabled BOOLEAN NOT NULL DEFAULT 0;`,
    `ALTER TABLE Agent ADD COLUMN temperature REAL;`,
    `ALTER TABLE Agent ADD COLUMN maxTokens INTEGER;`,
    `ALTER TABLE Agent ADD COLUMN addHistoryContext BOOLEAN NOT NULL DEFAULT 0;`,
    `ALTER TABLE Agent ADD COLUMN historySessions INTEGER;`,
    `ALTER TABLE Agent ADD COLUMN addStateContext BOOLEAN NOT NULL DEFAULT 0;`,
    `ALTER TABLE Agent ADD COLUMN knowledgeMode TEXT;`,
    `ALTER TABLE Agent ADD COLUMN knowledgeMaxResults INTEGER;`,
    `ALTER TABLE Agent ADD COLUMN knowledgeAddReferences BOOLEAN NOT NULL DEFAULT 1;`,
    `ALTER TABLE Agent ADD COLUMN knowledgeContextFormat TEXT;`,
    `ALTER TABLE Agent ADD COLUMN knowledgeFilters TEXT;`,
    `ALTER TABLE Agent ADD COLUMN visibility TEXT NOT NULL DEFAULT 'private';`,
    `ALTER TABLE Tool ADD COLUMN description TEXT;`,
    `ALTER TABLE Tool ADD COLUMN callName TEXT;`,
    `ALTER TABLE Tool ADD COLUMN transport TEXT;`,
    `ALTER TABLE Tool ADD COLUMN endpoint TEXT;`,
    `ALTER TABLE Tool ADD COLUMN method TEXT;`,
    `ALTER TABLE Tool ADD COLUMN authRef TEXT;`,
    `ALTER TABLE Tool ADD COLUMN timeoutMs INTEGER;`,
    `ALTER TABLE Tool ADD COLUMN visibility TEXT NOT NULL DEFAULT 'private';`,
    `ALTER TABLE KnowledgeSource ADD COLUMN sourceType TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN sourceConfig TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN chunkSize INTEGER;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN chunkOverlap INTEGER;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN chunkStrategy TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN embeddingProvider TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN embeddingModel TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN vectorStoreProvider TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN vectorStoreIndex TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN retrievalMode TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN searchType TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN maxResults INTEGER;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN rerankerProvider TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN rerankerModel TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN metadataFilter TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN contextFormat TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN addContextInstructions BOOLEAN NOT NULL DEFAULT 0;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN addReferences BOOLEAN NOT NULL DEFAULT 1;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN syncStatus TEXT DEFAULT 'idle';`,
    `ALTER TABLE KnowledgeSource ADD COLUMN lastSyncedAt DATETIME;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN lastSyncError TEXT;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN indexedDocuments INTEGER NOT NULL DEFAULT 0;`,
    `ALTER TABLE KnowledgeSource ADD COLUMN visibility TEXT NOT NULL DEFAULT 'private';`,
  ];
  for (const statement of alterSql) {
    try {
      await prisma.$executeRawUnsafe(statement);
    } catch {
      // Column already exists (or table not yet created in edge cases).
    }
  }

  const backfillSql = [
    `UPDATE Agent SET visibility = CASE WHEN isGlobal = 1 THEN 'shared' ELSE 'private' END WHERE visibility IS NULL OR visibility = '';`,
    `UPDATE Tool SET visibility = CASE WHEN teamId IS NULL THEN 'shared' ELSE 'private' END WHERE visibility IS NULL OR visibility = '';`,
    `UPDATE KnowledgeSource SET visibility = 'private' WHERE visibility IS NULL OR visibility = '';`,
  ];
  for (const statement of backfillSql) {
    await prisma.$executeRawUnsafe(statement);
  }
}
